# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "sre-takehome-tfstate-211125593418"
    dynamodb_table = "sre-takehome-tf-locks"
    encrypt        = true
    key            = "environments/dev/resources/terraform.tfstate"
    region         = "us-east-1"
  }
}
